"""add lead_matches table

Revision ID: e8c7f65ce775
Revises: 20260501_0001
Create Date: 2026-05-01 13:06:49.197707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8c7f65ce775'
down_revision: Union[str, None] = '20260501_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_reason', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True, comment='matched, contacted, interested, purchased, rejected'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['tenant_leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lead_agent', 'lead_matches', ['lead_id', 'agent_id'], unique=True)
    op.create_index(op.f('ix_lead_matches_agent_id'), 'lead_matches', ['agent_id'], unique=False)
    op.create_index(op.f('ix_lead_matches_created_at'), 'lead_matches', ['created_at'], unique=False)
    op.create_index(op.f('ix_lead_matches_id'), 'lead_matches', ['id'], unique=False)
    op.create_index(op.f('ix_lead_matches_lead_id'), 'lead_matches', ['lead_id'], unique=False)
    op.create_index(op.f('ix_lead_matches_status'), 'lead_matches', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_matches_status'), table_name='lead_matches')
    op.drop_index(op.f('ix_lead_matches_lead_id'), table_name='lead_matches')
    op.drop_index(op.f('ix_lead_matches_id'), table_name='lead_matches')
    op.drop_index(op.f('ix_lead_matches_created_at'), table_name='lead_matches')
    op.drop_index(op.f('ix_lead_matches_agent_id'), table_name='lead_matches')
    op.drop_index('idx_lead_agent', table_name='lead_matches')
    op.drop_table('lead_matches')
    # ### end Alembic commands ###
